### ISSUE TITLE
UnboundLocalError: local variable 'json' referenced before assignment

### ISSUE THREAD

**Issue by Kee43** [whittlem/pycryptobot#101]
Hi, great work on the bot so far. I am getting this error when running the demo:

pi@pi:~/pycryptobot $ python3 pycryptobot.py --market BTC-GBP --granularity 3600 --sim fast --verbose 0
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release : v2.0.0 (commit: 913)                                 |
--------------------------------------------------------------------------------
|              Bot Mode : TEST - test trades using dummy funds :)              |
|           Bot Started : 2021-05-03 19:24:56.783798                           |
================================================================================
|          Sell At Loss : 0  --sellatloss 0                                    |
|       Trade Bull Only : False  --disablebullonly                             |
|          Use Buy MACD : True  --disablebuymacd                               |
|           Use Buy OBV : False  --disablebuyobv                               |
|     Use Buy Elder-Ray : False  --disablebuyelderray                          |
|      Crypto Recession : True  --disablecryptorecession                       |
|    Sell Fibonacci Low : True  --disablefailsafefibonaccilow                  |
|   Sell Fibonacci High : True  --disableprofitbankfibonaccihigh               |
|  Candlestick Reversal : True  --disableprofitbankreversal                    |
|              Telegram : True  --disabletelegram                              |
|                   Log : False  --disablelog                                  |
|               Tracker : False  --disabletracker                              |
================================================================================
2021-04-21 07:00:00 | BTC-GBP | 3600 | Close: 39789.08 | EMA12/26: 39789.08 = 39789.08 | MACD: 0.0 = 0.0WAIT 
2021-04-21 08:00:00 | BTC-GBP | 3600 | Close: 39927.68 | *^ EMA12/26: 39810.41 > 39799.35 ^* | *^ MACD: 11.05 > 2.21 ^* | BUY 
Traceback (most recent call last):
  File "/home/pi/pycryptobot/models/CoinbasePro.py", line 334, in authAPI
    resp = requests.get(self._api_url + uri, auth=self)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 317, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 548, in prepare_auth
    r = auth(self)
  File "/home/pi/pycryptobot/models/CoinbasePro.py", line 82, in __call__
    hmac_key = base64.b64decode(self._api_secret)
  File "/usr/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (85) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pycryptobot.py", line 931, in <module>
    executeJob(s, app, trading_data)
  File "pycryptobot.py", line 902, in executeJob
    executeJob(sc, app, trading_data)
  File "pycryptobot.py", line 687, in executeJob
    fee = float(price) * app.getTakerFee()
  File "/home/pi/pycryptobot/models/PyCryptoBot.py", line 1479, in getTakerFee
    return api.getTakerFee()
  File "/home/pi/pycryptobot/models/CoinbasePro.py", line 148, in getTakerFee
    fees = self.getFees()
  File "/home/pi/pycryptobot/models/CoinbasePro.py", line 127, in getFees
    df = self.authAPI('GET', 'fees')
  File "/home/pi/pycryptobot/models/CoinbasePro.py", line 397, in authAPI
    except json.decoder.JSONDecodeError as err:
UnboundLocalError: local variable 'json' referenced before assignment

I am running on a Raspberry Pi 3.

python3 --version
Python 3.7.3 (I saw in another issue a user said this was fine for a Pi as I'm not using docker)

**Comment by whittlem** [comment]
I think you may have a syntax error in your config.json. Can you email it to me without your API keys and I will take a look? michael@lifecycle-ps.com
