### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by yassirkachri** [whittlem/pycryptobot#125]
An error occurs many times this morning on 4 Bot that working well 

T$ python3.9 pycryptobot.py --granularity 900

Traceback (most recent call last):
  File "/home/ec2-user/ADA-EUR/models/CoinbasePro.py", line 342, in authAPI
    print ('error:', method.upper() + ' (' + '{}'.format(resp.status_code) + ') ' + self._api_url + uri + ' - ' + '{}'.format(resp.json()['message']))
  File "/home/ec2-user/.local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/ec2-user/ADA-EUR/models/CoinbasePro.py", line 342, in authAPI
    print ('error:', method.upper() + ' (' + '{}'.format(resp.status_code) + ') ' + self._api_url + uri + ' - ' + '{}'.format(resp.json()['message']))
  File "/home/ec2-user/.local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/ADA-EUR/pycryptobot.py", line 74, in <module>
    elif last_action == 'BUY' and account.getBalance(app.getBaseCurrency()) < 0.001:
  File "/home/ec2-user/ADA-EUR/models/TradingAccount.py", line 230, in getBalance
    df = model.getAccounts()
  File "/home/ec2-user/ADA-EUR/models/CoinbasePro.py", line 100, in getAccounts
    df = self.authAPI('GET', 'accounts')
  File "/home/ec2-user/ADA-EUR/models/CoinbasePro.py", line 397, in authAPI
    except json.decoder.JSONDecodeError as err:
UnboundLocalError: local variable 'json' referenced before assignment
**Expected behavior**

**Comment by yassirkachri** [comment]
in addition  it occurs just after :
2021-05-07 10:38:13 | BTC-EUR | 900 | Current Price: 46782.86
error: GET (500) https://api.pro.coinbase.com/fees - Internal Server Error.


2021-05-07 10:38:30 | ADA-EUR | 900 | Current Price: 1.3612
error: GET (500) https://api.pro.coinbase.com/fees - Internal Server Error.
Traceback (most recent call last):

**Comment by yassirkachri** [comment]
absolutely I am runing the last code

**Comment by whittlem** [comment]
Can you check now and confirm if you are still having this issue?

**Comment by yassirkachri** [comment]
I have  pulled the last code 
I don't get the error for the last days

**Comment by whittlem** [comment]
Thanks for letting me know.
