### ISSUE TITLE
1m granularity error Something went wrong

### ISSUE THREAD

**Issue by usama8800** [whittlem/pycryptobot#146]
**Describe the bug**
Choosing 1m granularity for Binance causes an error

**To Reproduce**
1. run with `--granularity 1m` on Binance exchange

**Expected behavior**
No crash on start

**Desktop (please complete the following information):**
 - OS: Win10
 - Python: 3.9.2

**Additional context**
```
Exception('Something went wrong!')
Traceback (most recent call last):
  File "pycryptobot\pycryptobot.py", line 1028, in <module>
    main()
  File "pycryptobot\pycryptobot.py", line 991, in main
    runApp()
  File "pycryptobot\pycryptobot.py", line 986, in runApp
    executeJob(s, app, state)
  File "pycryptobot\pycryptobot.py", line 97, in executeJob
    trading_data = app.getHistoricalData(app.getMarket(), app.getGranularity())
  File "pycryptobot\models\PyCryptoBot.py", line 1335, in getHistoricalData
    return api.getHistoricalData(market, granularity)
  File "pycryptobot\models\Binance.py", line 408, in getHistoricalData
    raise Exception('Something went wrong!')
Exception: Something went wrong!
```

The relevant code is missing a '1m' if block
```
            if granularity == '5m':
                resp = self.client.get_historical_klines(market, granularity, '2 days ago UTC')
                resp = resp[-300:]
            elif granularity == '15m':
                resp = self.client.get_historical_klines(market, granularity, '4 days ago UTC')
                resp = resp[-300:]
            elif granularity == '1h':
                resp = self.client.get_historical_klines(market, granularity, '13 days ago UTC')
                resp = resp[-300:]
            elif granularity == '6h':
                resp = self.client.get_historical_klines(market, granularity, '75 days ago UTC')
                resp = resp[-300:]
            elif granularity == '1d':
                resp = self.client.get_historical_klines(market, granularity, '251 days ago UTC')
            else:
                raise Exception('Something went wrong!')
```

**Comment by whittlem** [comment]
I have asked some questions on your PR. It looks like you branched off old code and will wipe out newer code. I see the fix you want to do so will fix this. I would advise not to trade on 1 minute graphs. You will almost surely lose out on fees. I would use 1 hour graphs. 15 minute as a minimum in good conditions.

**Comment by whittlem** [comment]
I implemented most of your PR manually. Should be working now.
