### ISSUE TITLE
Bot not selling on Binance 

### ISSUE THREAD

**Issue by mebell** [whittlem/pycryptobot#155]
I get the following error when trying to sell with Binance. Did a git pull yesterday (11th May). It shouldn't be trying to do anything with coinbase. Here is my setup:

{
"binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "",
        "api_secret" : "",
        "api_passphrase" : "",
        "config" : {
            "base_currency" : "DOGE",
            "quote_currency" : "AUD",
            "live" : 1,
            "sellatloss" : 0,
            "trailingstoploss": -2,
            "sellupperpcnt": 10,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "buypercent" : 75,
            "disablebuynearhigh" : 1,
            "sellatresistance" : 1,
            "autorestart" : 1
        }
    },

2021-05-11 18:00:00 | MKRBUSD | 1h | Close: 5274.94 | *^ EMA12/26: 5076.13 > 5068.67 ^* | ^ MACD: 7.45 > -39.43 ^ | SELL | Last Action: BUY | 1.25% (delta: 92.29)
support: 5255.14, resistance: 5449.51, fibonacci (l): 5185.44, fibonacci (u): 5437.56

 2021-05-11 18:00:00 | MKRBUSD 1h | Close: 5274.94 | SELL
 Fibonacci Retracement Levels: {'ratio0_5': 5185.44, 'ratio0_382': 5437.56} 

MKR balance before order: 0.0021
BUSD balance before order: 3.8322
ValueError('Coinbase Pro API URL is invalid')
Traceback (most recent call last):
  File "pycryptobot.py", line 991, in main
    runApp()
  File "pycryptobot.py", line 988, in runApp
    s.run()
  File "/Users/134393/anaconda3/lib/python3.7/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "pycryptobot.py", line 842, in executeJob
    resp = app.marketSell(app.getMarket(), float(account.getBalance(app.getBaseCurrency())), app.getSellPercent())
  File "/Users/134393/Work/pycryptobot/bot_3/models/PyCryptoBot.py", line 1623, in marketSell
    api = CBAuthAPI(self.getAPIKey(), self.getAPISecret(), self.getAPIPassphrase(), self.getAPIURL())
  File "/Users/134393/Work/pycryptobot/bot_3/models/CoinbasePro.py", line 51, in __init__
    raise ValueError('Coinbase Pro API URL is invalid')
ValueError: Coinbase Pro API URL is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pycryptobot.py", line 1028, in <module>
    main()
  File "pycryptobot.py", line 1007, in main
    runApp()
  File "pycryptobot.py", line 986, in runApp
    executeJob(s, app, state)
  File "pycryptobot.py", line 842, in executeJob
    resp = app.marketSell(app.getMarket(), float(account.getBalance(app.getBaseCurrency())), app.getSellPercent())
  File "/Users/134393/Work/pycryptobot/bot_3/models/PyCryptoBot.py", line 1623, in marketSell
    api = CBAuthAPI(self.getAPIKey(), self.getAPISecret(), self.getAPIPassphrase(), self.getAPIURL())
  File "/Users/134393/Work/pycryptobot/bot_3/models/CoinbasePro.py", line 51, in __init__
    raise ValueError('Coinbase Pro API URL is invalid')
ValueError: Coinbase Pro API URL is invalid

**Comment by edrickrenan** [comment]
This issue was fixed by https://github.com/whittlem/pycryptobot/pull/151.

**Comment by whittlem** [comment]
Thanks for confirming.
