### ISSUE TITLE
Error when setting --lastaction SELL

### ISSUE THREAD

**Issue by delphsmith** [whittlem/pycryptobot#232]
**Describe the bug**
Error when starting the bot with the parameter--lastaction SELL
(no pb without this CLI parameter, bot starting with lastaction:BUY because i already have some matic in my binance wallet)

**To Reproduce**
python3 pycryptobot.py --config ../Config/binance.json --market MATICBUSD --lastaction SELL
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'fees'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pycryptobot.py", line 40, in <module>
    state.last_buy_fee = float(df[df.action == 'buy']['fees'])
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'fees'

**Expected behavior**
bot starting with last action : SELL

**Desktop (please complete the following information):**
raspberry 3

**Additional context**
My config.json

{
    "binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "",
        "api_secret" : "",
        "config" : {
            "verbose" : 0,
            "graphs" : 0,
            "sellatloss" : 0,
            "granularity" : "1h",
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disableprofitbankreversal" : 0,
            "autorestart" : 1,
            "sellatresistance" : 1,
            "disablebullonly" : 1,
            "live" : 1,
            "buymaxsize" : "100"
        }
    },
    "telegram" : {
        "token" : "",
        "client_id" : ""
    }
}

**Comment by marianido** [comment]
Line 40: ------------------>  state.last_buy_fee = float(df[df.action == 'buy']['fees'])
Must be changed by: ----> state.last_buy_fee = state.last_buy_size * app.getTakerFee()

**Comment by whittlem** [comment]
Are you able to confirm you are still having an issue here? A lot of changes have been made to that part of the code recently and just want to confirm it's not already resolved before looking.

**Comment by marianido** [comment]
still there in my last pull.

**Comment by delphsmith** [comment]
yes, still there :-/

**Comment by sdroulers** [comment]
I confirm, had the same error this morning with argument `--lastaction SELL`

**Comment by whittlem** [comment]
This should be fixed now.
