### ISSUE TITLE
Bug Function app.getTakerFee()

### ISSUE THREAD

**Issue by biskuizera19** [whittlem/pycryptobot#234]
**Describe the bug**

The bot was fine. When the purchase signal was given, the error appeared in the app.getTakerFee () function

**To Reproduce**
2021-05-24 21:41:00 | ETHUSDT (BULL) | 1m | Close: 2621.5 | *v EMA12/26: 2639.9644 < 2640.1743 v* | *v MACD: -0.2099 < 0.7311 v* | v OBV: -1051.5205 (-170.1500%) v | ERI: sell | WAIT | Last Action: BUY | -1.0295% (delta: -24.62)
support: 2603.24, resistance: 2624.26, fibonacci (l): 2618.96, fibonacci (u): 2641.62
2021-05-24 21:42:00 | ETHUSDT (BULL) | 1m | Close: 2589.55 | v EMA12/26: 2632.2083 < 2636.4244 v | v MACD: -4.2161 < -0.2583 v | ^ OBV: -5643.2519 (436.68%) ^ | ERI: sell | WAIT | Last Action: BUY | -2.2357% (delta: -56.57)
support: 2575.0, resistance: 2603.24, fibonacci (l): 2567.49, fibonacci (u): 2596.3
KeyError('success')
Traceback (most recent call last):
  File "pycryptobot.py", line 1048, in main
    runApp()
  File "pycryptobot.py", line 1041, in runApp
    executeJob(s, app, state, trading_data)
  File "pycryptobot.py", line 996, in executeJob
    executeJob(sc, app, state, trading_data)
  File "pycryptobot.py", line 996, in executeJob
    executeJob(sc, app, state, trading_data)
  File "pycryptobot.py", line 996, in executeJob
    executeJob(sc, app, state, trading_data)
  [Previous line repeated 134 more times]
  File "pycryptobot.py", line 337, in executeJob
    state.last_buy_fee = round(state.last_buy_size * app.getTakerFee(), 8)
  File "C:\bot\models\PyCryptoBot.py", line 535, in getTakerFee
    return api.getTakerFee(self.getMarket())
  File "C:\bot\models\exchange\binance\api.py", line 132, in getTakerFee
    fees = self.getFees(market)
  File "C:\bot\models\exchange\binance\api.py", line 97, in getFees
    resp = self.client.get_trade_fee(symbol=market)
  File "C:\Users\Felipe\anaconda3\lib\site-packages\binance\client.py", line 2169, in get_trade_fee
    if not res['success']:
KeyError: 'success'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pycryptobot.py", line 1086, in <module>
    main()
  File "pycryptobot.py", line 1064, in main
    runApp()
  File "pycryptobot.py", line 1041, in runApp
    executeJob(s, app, state, trading_data)
  File "pycryptobot.py", line 996, in executeJob
    executeJob(sc, app, state, trading_data)
  File "pycryptobot.py", line 996, in executeJob
    executeJob(sc, app, state, trading_data)
  File "pycryptobot.py", line 996, in executeJob
    executeJob(sc, app, state, trading_data)
  [Previous line repeated 2 more times]
  File "pycryptobot.py", line 346, in executeJob
    sell_taker_fee=app.getTakerFee(),
  File "C:\bot\models\PyCryptoBot.py", line 535, in getTakerFee
    return api.getTakerFee(self.getMarket())
  File "C:\bot\models\exchange\binance\api.py", line 132, in getTakerFee
    fees = self.getFees(market)
  File "C:\bot\models\exchange\binance\api.py", line 97, in getFees
    resp = self.client.get_trade_fee(symbol=market)
  File "C:\Users\Felipe\anaconda3\lib\site-packages\binance\client.py", line 2169, in get_trade_fee
    if not res['success']:
KeyError: 'success'

(base) C:\bot>]

**Screenshots**
![erro bot](https://user-images.githubusercontent.com/53500890/119492827-e5211900-bd35-11eb-8521-6ae72c80d0fc.jpg)

**Desktop (please complete the following information):**
 - Windows 10
 - Python 3.7.8

**Comment by whittlem** [comment]
Can you confirm what version of python-binance you are using?

It should be 0.7.9

% python3 -m pip freeze | grep binance                                                                                                                                                 
python-binance==0.7.9

There is a breaking change in the latest version of the library.

**Comment by biskuizera19** [comment]
I have version 0.7.9.

Which one would be correct?

**Comment by emreeroglu** [comment]
I am having this one too but only for simulator.

**Comment by whittlem** [comment]
@biskuizera19, you have the correct version.

**Comment by biskuizera19** [comment]
I removed getTakerFee in the Binance api.py file and it worked

**Comment by biskuizera19** [comment]
Another problem was that my operating system clock was out of sync. So I synchronized and now everything works fine

**Comment by whittlem** [comment]
Thanks, I'll add some code to handle that error in getTakerFee more gracefully. Otherwise is this resolved?

**Comment by biskuizera19** [comment]
for me it's solved.....bot running normally

**Comment by whittlem** [comment]
Thanks should be fixed now. I put an additional check for that missing 'success' key as well.
