### ISSUE TITLE
Missing Modules 

### ISSUE THREAD

**Issue by reubadoob** [whittlem/pycryptobot#316]
**Describe the bug**
Missing modules errors

**To Reproduce**
`pi@raspberrypi:/home/pycryptobot $ sudo python3 pycryptobot.py --market BTC-GBP --granularity 3600 --sim fast --verbose 0
Traceback (most recent call last):
  File "pycryptobot.py", line 10, in <module>
    from models.PyCryptoBot import PyCryptoBot, truncate as _truncate
  File "/home/pycryptobot/models/PyCryptoBot.py", line 12, in <module>
    from models.Trading import TechnicalAnalysis
  File "/home/pycryptobot/models/Trading.py", line 11, in <module>
    from statsmodels.tsa.statespace.sarimax import SARIMAX, SARIMAXResultsWrapper
ModuleNotFoundError: No module named 'statsmodels'`

**Expected behavior**
Fun quick non-live demo

**Screenshots**
See out put above

**Desktop (please complete the following information):**
 - OS: Linux raspberrypi 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
- Python 3.7.3
- pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

**Comment by reubadoob** [comment]
Resolved by re-running :

`% sudo  python3 -m pip install -r requirements.txt`
