### ISSUE TITLE
Data range too small, setting granularity doesn't help

### ISSUE THREAD

**Issue by Vashiru** [whittlem/pycryptobot#339]
**Describe the bug**
I'm getting a data range too small error when attempting to trade SUN/USDT on Binance, even when changing the granularity.

I've tried the following configs:

**Granularity set to a fixed timeframe:**
```json
 "config" : {
            "base_currency" : "SUN",
            "quote_currency" : "USDT",
            "live" : 0,
            "verbose" : 0,
            "granularity": "5m", # Also tried 15m, 1h
            "sellatloss": 1,
            "trailingstoploss": -5,
            "disablebuynearhigh" : 1,
            "autorestart": 1
        }
```
**Errors and restarts with:**
```
2021-06-16 22:13:15 INFO     ================================================================================
Restarting application after exception: Exception('Data range too small.')
2021-06-16 22:13:46 CRITICAL Restarting application after exception: Exception('Data range too small.')
Exception('Data range too small.')
2021-06-16 22:13:47 CRITICAL Exception('Data range too small.')
Traceback (most recent call last):
  File "/app/models/Trading.py", line 611, in addSMA
    raise Exception('Data range too small.')
Exception: Data range too small.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/models/Trading.py", line 611, in addSMA
    raise Exception('Data range too small.')
Exception: Data range too small.
```

---

Granularity not set to enable smart switching:
```json
 "config" : {
            "base_currency" : "SUN",
            "quote_currency" : "USDT",
            "live" : 0,
            "verbose" : 0,
            "sellatloss": 1,
            "trailingstoploss": -5,
            "disablebuynearhigh" : 1,
            "autorestart": 1
        }
```
**Errors but continues to run:**
```
2021-06-16 22:17:55 INFO     ================================================================================
error: data frame length is < 300 (247)
2021-06-16 22:17:58 ERROR    error: data frame length is < 300 (247)
2021-06-14 03:00:00 | SUNUSDT (BEAR) | 1h | Close: 27.5720 | ^ EMA12/26: 26.7400 > 25.9594 ^ | ^ MACD: 0.7805 > 0.6253 ^^ OBV: -106780.4330 (39.6400%) ^ | ERI: sell |  | WAIT | Last Action: SELL
2021-06-16 22:17:58 INFO     2021-06-14 03:00:00 | SUNUSDT (BEAR) | 1h | Close: 27.5720 | ^ EMA12/26: 26.7400 > 25.9594 ^ | ^ MACD: 0.7805 > 0.6253 ^^ OBV: -106780.4330 (39.6400%) ^ | ERI: sell |  | WAIT | Last Action: SELL
Seasonal ARIMA model predicts the closing price will be 28.29 at 2021-06-14 06:00:00 (delta: 0.71)
2021-06-16 22:17:59 INFO     Seasonal ARIMA model predicts the closing price will be 28.29 at 2021-06-14 06:00:00 (delta: 0.71)
error: data frame length is < 300 (247)
2021-06-16 22:19:01 ERROR    error: data frame length is < 300 (247)
2021-06-16 22:19:02 | SUNUSDT (BEAR) | 1h | Current Price: 27.572
2021-06-16 22:19:02 INFO     2021-06-16 22:19:02 | SUNUSDT (BEAR) | 1h | Current Price: 27.572
```

---

Based on: https://github.com/whittlem/pycryptobot/issues/140#issuecomment-836246958 I would think that setting a finer granularity, would solve my issue. Seeing as 1h with smart switching gives "<300 (247)", I figured setting it to 15 minutes (4x 247 = 988), would solve the issue. The coin has also existed for longer than 300 hours on Binance, so I would've thought even hours would be fine?

**Expected behavior**
Bot would start trading

**Additional information**
It seems that right now the order book for SUN/USDT isn't loading either, so it might be Binance having issues on their end.

**EDIT:** Yeah at the moment Binance is reporting "Trading Suspended" when you actually look in the mobile app. So that might explain things. Also a different exchange (Poloniex) is reporting wallet maintenance on Twitter. Still doubt that it's parsing the granularity correctly so leaving the issue open for now.

**Comment by Vashiru** [comment]
Market maintenance has ended, ran some more tests. Seems to work correctly now.
