### ISSUE TITLE
MarginHelper.py float division by zero

### ISSUE THREAD

**Issue by antonp01** [whittlem/pycryptobot#340]
**Describe the bug**
just did a git pull to update source, and tried running --sim fast and got division by zero.

**To Reproduce**
```
python3.9 pycryptobot.py --sim fast
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|                Release : v2.32.0                                             |
-----------------------------------------------------------------------------
|               Bot Mode : TEST - test trades using dummy funds :)             |
|            Bot Started : 2021-06-16 14:16:33.836437                          |
================================================================================
|           Sell At Loss : True  --sellatloss True                             |
|     Sell At Resistance : False  --sellatresistance                           |
|        Trade Bull Only : False  --disablebullonly                            |
|          Buy Near High : True  --disablebuynearhigh                          |
|           Use Buy MACD : True  --disablebuymacd                              |
|            Use Buy OBV : True  --disablebuyobv                               |
|      Use Buy Elder-Ray : True  --disablebuyelderray                          |
|     Sell Fibonacci Low : True  --disablefailsafefibonaccilow                 |
|   Candlestick Reversal : True  --disableprofitbankreversal                   |
|               Telegram : True  --disabletelegram                             |
|                    Log : True  --disablelog                                  |
|                Tracker : True  --disabletracker                              |
|       Auto restart Bot : False  --autorestart                                |
================================================================================
2021-06-13 18:15:00 | BTC-USD | 900 | Close: 37514.9500 | EMA12/26: 37514.9500 = 37514.9500 | MACD: 0.0000 = 0.0000OBV: 406.4252 (0.0000%)ERI: |  | WAIT | Last Action: WAIT
2021-06-13 18:30:00 | BTC-USD | 900 | Close: 37375.6400 | *v EMA12/26: 37493.5176 < 37504.6307 v* | *v MACD: -11.1130 < -2.2226 v*v OBV: 237.5648 (-41.5500%) v | ERI: sell |  | SELL | Last Action: WAIT
ZeroDivisionError('float division by zero')
Traceback (most recent call last):
  File "/home/anton/pycryptobot/BTC/models/helper/MarginHelper.py", line 28, in calculate_margin
    margin = round((profit / buy_size) * 100, precision)
ZeroDivisionError: float division by zero
```

**Comment by Vashiru** [comment]
Running into the same issue on Binance KAVA/USDT (live) just now. v2.32.0 as well.

In my case I do own some KAVA, but it's pending in a sell order. Maybe that's tripping up the bot?

**Logs:**
```
Restarting application after exception: ZeroDivisionError('float division by zero')

ZeroDivisionError('float division by zero')

Traceback (most recent call last):

  File "/app/models/helper/MarginHelper.py", line 28, in calculate_margin

    margin = round((profit / buy_size) * 100, precision)

ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/models/helper/MarginHelper.py", line 28, in calculate_margin

    margin = round((profit / buy_size) * 100, precision)

ZeroDivisionError: float division by zero
```

**Comment by stefanoregis** [comment]
same problem on my side

**Comment by Vashiru** [comment]
@arma6655 Thanks for the clear description, I've opened a pull request to get it fixed.

**Comment by germainlefebvre4** [comment]
Opened #367 to solve another case of division by zero from MarginHelper.py.

This time it is because the retrieved orders contains orders `filled` and `new` (made by user on limit for example).
The `new` orders does not contain any `buy_size` real value. So it is converted as a `0` (zero) and the calling method raise this error.
