### ISSUE TITLE
Unexpected stop on the last version

### ISSUE THREAD

**Issue by hellresistor** [whittlem/pycryptobot#358]
**Describe the bug**
pycryptobot stops

**To Reproduce**
1. Just running on a VPS (with static ip)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: debian 10  VPS
 - Version v2.38.0
 
**Additional context**

```
2021-06-23 23:18:59 | BTCEUR | 15m | Current Price: 28050.01 | Margin: -6.40316714 | Profit: -1.24928743
Exception: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
Error on creating instance of AuthAPI Client. Trying again... Attempt: 0
ConnectionError(ReadTimeoutError("HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out."))
Traceback (most recent call last):
  File "/home/user/ATOM-BTC/models/exchange/binance/api.py", line 489, in getTicker
    return (self.getTime().strftime('%Y-%m-%d %H:%M:%S'), float('{:.8f}'.format(float(resp['price']))))
AttributeError: 'NoneType' object has no attribute 'strftime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/bin/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.venvs/lib/python3.9/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.venvs/lib/python3.9/site-packages/requests/models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out.
```

**Comment by hellresistor** [comment]
Get other situation:
 1- Bot is running with granularity 15m in command (because defined in config.yml file, will not detect the 15m, and start with 1hinstead)
 2- During bot running, open new other terminal/session, I have executed the script_get_fee , script_get_order and script_get_time. with sucess output
 3- Bot Stops with this error.
 
 ```
2021-06-24 05:54:28 | BTCEUR | 15m | Current Price: 27583.42 | Margin: -7.9600773 | Profit: -1.55304778
Restarting application after exception: ZeroDivisionError('float division by zero')
ZeroDivisionError('float division by zero')
Traceback (most recent call last):
  File "/home/user/ATOM-BTC/models/helper/MarginHelper.py", line 28, in calculate_margin
    margin = round((profit / buy_size) * 100, precision)
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/ATOM-BTC/models/helper/MarginHelper.py", line 28, in calculate_margin
    margin = round((profit / buy_size) * 100, precision)
ZeroDivisionError: float division by zero
```
