### ISSUE TITLE
Why close connection randomly?

### ISSUE THREAD

**Issue by hellresistor** [whittlem/pycryptobot#362]
**Describe the bug**
Random ..
Sometimes restart the bot with success othertimes exit but with different error like this.
Exemple Telegrambot bellow.

**To Reproduce**
1. Just Run and wait

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: debian 10 (VPS)
 - Version 2.38

**Additional context**
Telegram bot message

```
bothole, [26.06.21 13:25]
Starting Binance bot for ADAEUR using granularity 15m. Smartswitch disabled

bothole, [26.06.21 13:25]
ADAEUR (15m) BUY at Close: 1.0531

bothole, [27.06.21 01:25]
ADAEUR (15m) ! Profit Bank Triggered (Selling At Resistance)

bothole, [27.06.21 01:25]
ADAEUR (15m) SELL at Close: 1.0767 (margin: 2.0876%, (delta: 0.0236)

bothole, [27.06.21 03:40]
Auto restarting bot for ADAEUR after exception: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

bothole, [27.06.21 03:44]
Bot for ADAEUR got an exception: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

bothole, [27.06.21 08:52]
Starting Binance bot for ADAEUR using granularity 15m. Smartswitch disabled

bothole, [27.06.21 17:15]
ADAEUR (15m) BUY at Close: 1.0653

bothole, [27.06.21 23:12]
ADAEUR (15m) ! Profit Bank Triggered (Selling At Resistance)

bothole, [27.06.21 23:12]
ADAEUR (15m) SELL at Close: 1.0885 (margin: 2.0341%, (delta: 0.0233)

bothole, [27.06.21 23:15]
ADAEUR (15m) *** Candlestick Detected: Three White Soldiers ("Strong - Reversal - Bullish Pattern - Up")

bothole, [28.06.21 05:49]
Auto restarting bot for ADAEUR after exception: BinanceAPIException(<Response 504>, 504, '<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n')
```

**Comment by hellresistor** [comment]
And getting this

```
2021-06-29 03:46:14 | RUNEUSDT | 15m | Current Price: 6.425
2021-06-29 03:47:20 | RUNEUSDT | 15m | Current Price: 6.412
2021-06-29 03:48:27 | RUNEUSDT | 15m | Current Price: 6.405
2021-06-29 03:49:34 | RUNEUSDT | 15m | Current Price: 6.421
2021-06-29 03:50:40 | RUNEUSDT | 15m | Current Price: 6.428
2021-06-29 03:51:47 | RUNEUSDT | 15m | Current Price: 6.413
2021-06-29 03:52:53 | RUNEUSDT | 15m | Current Price: 6.426
2021-06-29 03:54:00 | RUNEUSDT | 15m | Current Price: 6.432
2021-06-29 03:55:06 | RUNEUSDT | 15m | Current Price: 6.415
2021-06-29 03:56:13 | RUNEUSDT | 15m | Current Price: 6.405
2021-06-29 03:57:19 | RUNEUSDT | 15m | Current Price: 6.427
2021-06-29 03:58:25 | RUNEUSDT | 15m | Current Price: 6.419
2021-06-29 03:59:32 | RUNEUSDT | 15m | Current Price: 6.409

================================================================================
 |         Iteration : 8                                                       |
 |         Timestamp : 2021-06-29 04:00:00                                     |
--------------------------------------------------------------------------------
 |             Close : 6.4109                                                  |
 |             EMA12 : 6.4237                                                  |
 |             EMA26 : 6.4253                                                  |
 |    Crossing Above : False                                                   |
 |   Currently Above : False                                                   |
 |    Crossing Below : True                                                    |
 |   Currently Below : True                                                    |
 |         Condition : EMA12 is currently crossing below EMA26                 |
 |             SMA20 : 6.4440                                                  |
 |            SMA200 : 5.9793                                                  |
--------------------------------------------------------------------------------
 |              MACD : -0.0017                                                 |
 |            Signal : 0.0078                                                  |
 |   Currently Above : False                                                   |
 |   Currently Below : True                                                    |
 |         Condition : MACD is currently below Signal and has crossed over     |
--------------------------------------------------------------------------------
 |            Action : SELL                                                    |
================================================================================
 |            Margin : 0%                                                      |
================================================================================
--------------------------------------------------------------------------------
|                      *** Executing LIVE Sell Order ***                        |
--------------------------------------------------------------------------------
RUNE balance before order: 0.7
USDT balance before order: 0.0
*** getTradeFee(RUNEUSDT) - missing "tradeFee" ***
[{'symbol': 'RUNEUSDT', 'makerCommission': '0.001', 'takerCommission': '0.001'}]
Order quantity after rounding and fees: 0.698
29-06-2021 04:00:43 Binance  marketSell APIError(code=-1013): Filter failure: MIN_NOTIONAL
RUNE balance after order: 0.7
USDT balance after order: 0.0
last_action change detected from SELL to BUY
2021-06-29 04:01:52 | RUNEUSDT | 15m | Current Price: 6.44
2021-06-29 04:02:58 | RUNEUSDT | 15m | Current Price: 6.46
2021-06-29 04:04:05 | RUNEUSDT | 15m | Current Price: 6.481
2021-06-29 04:05:12 | RUNEUSDT | 15m | Current Price: 6.503
ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/domato/.venvs/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
