### ISSUE TITLE
Quote Currency

### ISSUE THREAD

**Issue by rwl816** [whittlem/pycryptobot#376]
I am unable to get a bot to work using the crypto markets.  Would it be possible to make some code changes to allow for the "quote currency" to be set to something other than the fiat currency markets?  It would be nice to be able to set up a bot for YFI-BTC or ADA-ETH.  This would also make it possible to run multiple bots in the same coinbase portfolio as long as the base currencies are different and the quote currencies are different.

**Comment by hebawom** [comment]
I haven't done this myself, but I believe others are doing this in the current code base - without modifications.
Quote currency can be what you declare it.

**Comment by rwl816** [comment]
@hebawom Thanks.  I tried a bot setup for YFI-BTC and got it to successfully trade...Yay.  However, I am really wanting to set up for XLM-BTC and I'm getting errors:
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|                Release : v2.45.1                                             | 
-----------------------------------------------------------------------------
|                 Market : XLM-BTC                                             | 
|            Granularity : 300 seconds                                         | 
-----------------------------------------------------------------------------
|               Bot Mode : LIVE - live trades using your funds!                | 
|            Bot Started : 2021-07-07 15:13:02.609038                          | 
================================================================================
|           Sell At Loss : False  --sellatloss False                           | 
|     Sell At Resistance : False  --sellatresistance                           | 
|        Trade Bull Only : False  --disablebullonly                            | 
|          Buy Near High : False  --disablebuynearhigh                         | 
|           Use Buy MACD : True  --disablebuymacd                              | 
|            Use Buy OBV : True  --disablebuyobv                               | 
|      Use Buy Elder-Ray : False  --disablebuyelderray                         | 
|     Sell Fibonacci Low : False  --disablefailsafefibonaccilow                | 
|   Candlestick Reversal : True  --disableprofitbankreversal                   | 
|               Telegram : False  --disabletelegram                            | 
|                    Log : True  --disablelog                                  | 
|                Tracker : True  --disabletracker                              | 
|       Auto restart Bot : True  --autorestart                                 | 
================================================================================
Restarting application after exception: Exception('XLM-BTC is unsuitable for trading, quote price is less than 0.0001!')
Exception('XLM-BTC is unsuitable for trading, quote price is less than 0.0001!')
Traceback (most recent call last):
  File "/home/user1/PyCryptoBot/XLM-BTC-bot1/pycryptobot.py", line 160, in executeJob
    raise Exception(app.getMarket() + ' is unsuitable for trading, quote price is less than 0.0001!')
Exception: XLM-BTC is unsuitable for trading, quote price is less than 0.0001!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/PyCryptoBot/XLM-BTC-bot1/pycryptobot.py", line 160, in executeJob
    raise Exception(app.getMarket() + ' is unsuitable for trading, quote price is less than 0.0001!')
Exception: XLM-BTC is unsuitable for trading, quote price is less than 0.0001!

**Comment by whittlem** [comment]
I see what the problem is here. XLM is a really low cost crypto and BTC is really high priced. So the cost of XLM in BTC is a lot less than 0.0001. Probably just need to adjust in the validation. How much XLM are you trying to buy and how much is that in BTC? At least that will give us an indication of what sort of precision we need.

**Comment by rwl816** [comment]
@whittlem Thanks for considering adding this.  I have 0.0123 BTC (~$400) that I'm trying to start the bot with, using 100% of the BTC to buy XLM.

**Comment by lazydroid** [comment]
@whittlem binance provides the limits and precisions for all tradable pairs, we don't have to guess, just request that information from the exchange and use it.

**Comment by bydesign** [comment]
@whittlem I'm running into a similar problem on Coinbase using SHIB-USD.
`Bot for SHIB-USD got an exception: Exception('SHIB-USD is unsuitable for trading, quote price is less than 0.0001!')`

Looks like the current trading price for SHIB is 0.00001047 USD. How can I work around this with PyCryptoBot?
