### ISSUE TITLE
V3.0.0 KeyError: 'currency'

### ISSUE THREAD

**Issue by Olney1** [whittlem/pycryptobot#420]
Error: GET (400) https://api.binance.com/api/v3/account - Timestamp for this request is outside of the recvWindow.
KeyError('currency')
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'currency'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'currency'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'currency'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'currency'

***

Updated to latest Pandas available to RPi and installed requirements.

**Comment by sansal54** [comment]
Same error occurs on version 3.1.1 as well.

**Comment by jegb** [comment]
also in latest 3.2.2 
`Auto restarting bot for BTCBUSD after exception: KeyError('currency')`

**Comment by SentBackInTime** [comment]
Still the same issue here on latest and now with this traceback:

ConnectionError: https://api.binance.com
Exception('Data range too small.')
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'currency'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'currency'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/DOGE/pycryptobot/models/Trading.py", line 1052, in addSMA
    raise Exception("Data range too small.")
Exception: Data range too small.

**Comment by jegb** [comment]
could try to catch those exceptions, so the bot is not interrupted, right?

**Comment by edrickrenan** [comment]
Hey @Olney1, @jegb and @sansal54. Is this still happening?

**Comment by jegb** [comment]
not any more, there are binance api issues in my opinion.

**Comment by edrickrenan** [comment]
Ok, Thanks. I'll close this issue then.
