### ISSUE TITLE
statgroup not parsed in binance 

### ISSUE THREAD

**Issue by jegb** [whittlem/pycryptobot#489]
**Describe the bug**
When I set stat group list I get market error 

**To Reproduce**
1. Go to : python pycryptobot.py --exchange binance --stats --statgroup BTCBUSD ETHBUSD
2. error message:
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'market'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/username/Documents/workspace/pycryptobot/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'market'

**Expected behavior**
same behaviour as in coinbase: https://t.me/pycryptobotchat/24296

**Screenshots**
https://t.me/pycryptobotchat/24331

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jegb** [comment]
I have edited the config file, and now command level works, but on debugging mode the markets are not split.
