### ISSUE TITLE
tlegram bot problem]

### ISSUE THREAD

**Issue by anthonyk2923** [whittlem/pycryptobot#556]
pi@raspberrypi:~/pycryptobot $ python telegram_bot.py
Traceback (most recent call last):
  File "/home/pi/pycryptobot/telegram_bot.py", line 1143, in <module>
    main()
  File "/home/pi/pycryptobot/telegram_bot.py", line 1064, in main
    botconfig = TelegramBot()
  File "/home/pi/pycryptobot/telegram_bot.py", line 179, in __init__
    self.config = json.load(json_file)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 30 column 5 (char 780)

tHIS HAPPEND WHEN I run rasp pi telegram_bot.py I have python 3,9,0]

**Comment by notoriousBLP** [comment]
we helped you fix this in chat...can you close?
