### ISSUE TITLE
ValueError: numpy.ndarray size changed

### ISSUE THREAD

**Issue by Infini7y** [whittlem/pycryptobot#588]
I've followed the steps to install Python 3.9 and when attempting to run the bot I get the following error:

`pi@raspberrypi:~/pycryptobot-shib/pycryptobot $ python3 pycryptobot.py
Traceback (most recent call last):
  File "/home/pi/pycryptobot-shib/pycryptobot/pycryptobot.py", line 14, in <module>
    import pandas as pd
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/__init__.py", line 30, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 44 from C header, got 40 from PyObject`

I've tried `pip install numby` but that doesn't resolve the issue and I've been unable to get the bot running successfully. 

Any help would be appreciated!

**Comment by achillebnt** [comment]
I resoled with: 
pip install --upgrade numpy
