### ISSUE TITLE
Error with binance lib

### ISSUE THREAD

**Issue by Labbs** [whittlem/pycryptobot#61]
Hello,
I'm trying to run the bot with binance and I have an error

<details>
<summary>Details</summary>

--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|            Market : BTCDOGE                                                  |
|       Granularity : 1h                                                       |
--------------------------------------------------------------------------------
|          Bot Mode : TEST - test trades using dummy funds :)                  |
|       Bot Started : 2021-04-20 15:42:03.872121                               |
================================================================================
Traceback (most recent call last):
  File "/Users/jeremmm/pycryptobot/pycryptobot.py", line 870, in <module>
    executeJob(s, app)
  File "/Users/jeremmm/pycryptobot/pycryptobot.py", line 89, in executeJob
    trading_data = app.getHistoricalData(app.getMarket(), app.getGranularity())
  File "/Users/jeremmm/pycryptobot/models/PyCryptoBot.py", line 790, in getHistoricalData
    return api.getHistoricalData(market, granularity)
  File "/Users/jeremmm/pycryptobot/models/Binance.py", line 224, in getHistoricalData
    resp = self.client.get_historical_klines(market, granularity, '13 days ago UTC')
  File "/Users/jeremmm/pycryptobot/env/lib/python3.9/site-packages/binance/client.py", line 873, in get_historical_klines
    return self._historical_klines(symbol, interval, start_str, end_str=None, limit=500, spot=True)
  File "/Users/jeremmm/pycryptobot/env/lib/python3.9/site-packages/binance/client.py", line 917, in _historical_klines
    first_valid_ts = self._get_earliest_valid_timestamp(symbol, interval, spot)
  File "/Users/jeremmm/pycryptobot/env/lib/python3.9/site-packages/binance/client.py", line 846, in _get_earliest_valid_timestamp
    kline = self._klines(spot=spot,
  File "/Users/jeremmm/pycryptobot/env/lib/python3.9/site-packages/binance/client.py", line 829, in _klines
    return self.get_klines(**params)
  File "/Users/jeremmm/pycryptobot/env/lib/python3.9/site-packages/binance/client.py", line 817, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "/Users/jeremmm/pycryptobot/env/lib/python3.9/site-packages/binance/client.py", line 320, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/Users/jeremmm/pycryptobot/env/lib/python3.9/site-packages/binance/client.py", line 265, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/Users/jeremmm/pycryptobot/env/lib/python3.9/site-packages/binance/client.py", line 260, in _request
    return self._handle_response()
  File "/Users/jeremmm/pycryptobot/env/lib/python3.9/site-packages/binance/client.py", line 313, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

</details>

```
{
  "binance": {
    "api_url": "https://api.binance.com",
    "api_key": "<truncate>",
    "api_secret": "<truncate>",
    "config": {
      "base_currency": "BTC",
      "quote_currency": "DOGE",
      "granularity": "1h",
      "live": 0,
      "verbose": 1
    }
  }
}
```

Have you an idea about this?

Thanks

**Comment by arby1108** [comment]
Binance Testnet have limited symbols, there is not any BTC-DOGE, so try DOGE-USDT instead:

{
  "binance": {
    "api_url": "https://api.binance.com",
    "api_key": "<truncate>",
    "api_secret": "<truncate>",
    "config": {
      "base_currency": "DOGE",
      "quote_currency": "USDT",
      "granularity": "1h",
      "live": 0,
      "verbose": 1
    }
  }
}

**Comment by whittlem** [comment]
Just had a look at:
https://www.binance.com/en/markets

I think you have it the wrong way around...

base_currency is "DOGE"
quote_currency is "BTC"

There is no "BTCDOGE" market, only "DOGEBTC".
