### ISSUE TITLE
BinanceAPIException: Timestamp for this request was 1000ms ahead of the server's time

### ISSUE THREAD

**Issue by ftunholm** [whittlem/pycryptobot#64]
Hi,

I just encountered this issue (pasted stack trace in screen dump). Had the bot running for like 12h. Might be of interest for you.

Thanks for a cool bot!

![image](https://user-images.githubusercontent.com/8871986/115616110-139f7480-a2f0-11eb-9026-37c0efa2031e.png)

**Comment by whittlem** [comment]
Thanks, and glad you like the bot.

That message looks like you have very high latency to the exchange. Could that be?

**Comment by ftunholm** [comment]
Hi,

It seems I have 25-30ms latency might be that it spiked at that occasion. Generally I don't have any latency issues. I could see now when I got home that the bot failed earlier today with another exception but very similar.

`Traceback (most recent call last):
  File "C:\Users\Metadeath\Documents\GitHub\PyCryptoTrader\DOGEEUR_Binance\pycryptobot.py", line 872, in <module>
    s.run()
  File "C:\Users\Metadeath\AppData\Local\Programs\Python\Python39\lib\sched.py", line 151, in run
    action(*argument, **kwargs)
  File "C:\Users\Metadeath\Documents\GitHub\PyCryptoTrader\DOGEEUR_Binance\pycryptobot.py", line 832, in executeJob
    account.saveTrackerCSV(app.getMarket())
  File "C:\Users\Metadeath\Documents\GitHub\PyCryptoTrader\DOGEEUR_Binance\models\TradingAccount.py", line 293, in saveTrackerCSV
    df = self.getOrders(market, '', 'done')
  File "C:\Users\Metadeath\Documents\GitHub\PyCryptoTrader\DOGEEUR_Binance\models\TradingAccount.py", line 94, in getOrders
    resp = self.client.get_all_orders(symbol=market)
  File "C:\Users\Metadeath\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1713, in get_all_orders
    return self._get('allOrders', True, data=params)
  File "C:\Users\Metadeath\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 292, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\Metadeath\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 242, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\Metadeath\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 237, in _request
    return self._handle_response()
  File "C:\Users\Metadeath\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 285, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request is outside of the recvWindow.`

**Comment by whittlem** [comment]
I think you may be right about syncing your clock. Maybe it's slightly out causing it to not align properly with the exchange. Try using NTP.
