### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by th0rnbr** [whittlem/pycryptobot#73]
Hi!

Here in my environment, the bot keeps running for a random time (something between 10 - 30 minutes), then suddenly it halts giving connection errors.  Any ideas what is going on?

Here goes part of the error log:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

**Comment by whittlem** [comment]
I'm not entirely sure what that could be. 

1. What are you running the bot(s) on?
2. Which exchange are you using?
3. Does it happen every time?
4. How many bots are you running?

Can you make sure all your libraries are up to date?
"python3 -m pip install --upgrade pip"
"python3 -m pip list --outdated"

**Comment by th0rnbr** [comment]
Hi! 
I'm running on a MacOS Catalina (10.15.7)[1], using binance [2], it happens every time (sometime between 10 - 30 minutes while running)[3]. I'm running just one bot right now[4]. 

There were 2 libraries outdated (idna and setuptools), so I update them. Although, even with the most recent libraries, it keeps giving connection errors.

**Comment by whittlem** [comment]
I have the same MacOS as you and mine works.

Maybe you have an SSL issue. What versions are you using?

% python -c "import ssl; print (ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1k  25 Mar 2021

% python -c "from OpenSSL.SSL import SSLeay_version, SSLEAY_VERSION; print (SSLeay_version(SSLEAY_VERSION))"
b'OpenSSL 1.1.1j  16 Feb 2021'

**Comment by th0rnbr** [comment]
Hi. I think OpenSSL is already up to date:

% python -c "import ssl; print (ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1k  25 Mar 2021

% python -c "from OpenSSL.SSL import SSLeay_version, SSLEAY_VERSION; print (SSLeay_version(SSLEAY_VERSION))"
b'OpenSSL 1.1.1k  25 Mar 2021'

**Comment by letsautom8** [comment]
You could try installing a virtual environment to run your bot on - so no other libraries could mess with it.
Install virtual env

```$ pip3 install virtualenv```

Install virtual env wrapper (optional but will help setup your environment a bit faster)

```
$ pip3 install virtualenvwrapper
$ export WORKON_HOME=~/envs
$ mkdir -p $WORKON_HOME
$ source /usr/local/bin/virtualenvwrapper.sh
```

Note: you could place the last 3 lines from above to your bash/zsh profile

```
git clone https://github.com/whittlem/pycryptobot.git pycryptobot
cd pycryptobot
mkvirtualenv pycryptobot
pip install -r requirements.txt
python pycryptobot.py --market BTC-GBP --granularity 3600 --live 1 --verbose 0 --selllowerpcnt -2
```

**Comment by whittlem** [comment]
Thanks @letsautom8, that sounds like a good solution. @th0rnbr, can you try it and let us know if it resolves your issue?

@letsautom8, I see you are using "--selllowerpcnt". You may want to try "--trailingstoploss". I added it recently. Instead of having a fixed sell at -2% margin it would set the sell -2% under the current buy high. For example if you set "--trailingstoploss -2" if the margin goes up to 10% and then drops to 8% it will sell because the price dropped -2% from the high of the current buy.

**Comment by slygodhimself** [comment]
HI, THANKS!!
