### ISSUE TITLE
Run tests using config files

### ISSUE THREAD

**Issue by krzysztofMajchrzak-GIT** [whittlem/pycryptobot#798]
I was trying to run a few tests using configuration files but can't get it to work. So it seems like it is impossible to run bot with config file without providing API key. How to run tests using json files?

My command (I am locally build docker image):
`sudo docker run -it -v ./001.json:/app/config.json --rm --user pycryptobot pycryptobot/pycryptobot`

My Json config file:
```
"binance": {
    "config": {
        "exchange": binance,
        "market": ETHUSDT,
        "autorestart": 1,
        "base_currency": "ETH",
        "disablebuynearhigh": 1,
        "granularity": "15m",
        "nobuynearhighpcnt": 1,
        "nosellmaxpcnt": 3,
        "nosellminpcnt": -9,
        "quote_currency": "USDT",
        "sellatresistance": 1,
        "selllowerpcnt": -12,
        "trailingbuypcnt": 1,
        "trailingstoploss": -1,
        "trailingstoplosstrigger": 3,
        "sim": fast,
        "simstartingdate": "2023-01-01"
    }
}
```

And the error i get:

````
Traceback (most recent call last):
  File "/app/models/config/binance_parser.py", line 105, in parser
    with open(app.api_key_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'binance.key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pycryptobot.py", line 21, in <module>
    main()
  File "/app/pycryptobot.py", line 12, in main
    app = PyCryptoBot()
  File "/app/controllers/PyCryptoBot.py", line 78, in __init__
    super(PyCryptoBot, self).__init__(filename=self.config_file, exchange=exchange)
  File "/app/models/BotConfig.py", line 180, in __init__
    self.read_config()
  File "/app/models/BotConfig.py", line 230, in read_config
    binanceConfigParser(self, self.config[self.exchange.value], self.cli_args)
  File "/app/models/config/binance_parser.py", line 111, in parser
    raise RuntimeError(f"Unable to read {app.api_key_file}")
RuntimeError: Unable to read binance.key
````

Thank you in advance.

**Comment by whittlem** [comment]
I am on holiday now. I will respond when I am back. Take a look at the unit tests. You can see how it was done there.
