### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by djgalloway** [whittlem/pycryptobot#81]
This actually happened after a couple days of running.  I would have expected it immediately if the json was invalid.

```
$ cat bitcoin/pycryptobot.json
{
    "coinbasepro" : {
        "api_url" : "https://api.pro.coinbase.com",
        "api_key" : "XXXXX",
        "api_secret" : "XXXXX",
        "api_passphrase" : "XXXXX",
        "config" : {
            "base_currency" : "BTC",
            "quote_currency" : "USD",
            "granularity" : "10m",
            "live" : 1,
            "verbose" : 0
        }
    },
    "telegram" : {
        "token" : "XXXXX",
        "client_id" : "XXXXX"
    }
}
```

I understand `granularity` is supposed to be in seconds for Coinbase Pro but pycryptobot ignores that field anyway.  No matter what I put in there, the container always started with 3600.

Here's the full logs from the container.

```
2021-04-26 23:00:00 | BTC-USD (BEAR) | 3600 | Close: 53521.3 | ^ EMA12/26: 53497.23 > 52816.81 ^ | v MACD: 680.42 < 810.81 v | ^ OBV: -13682.0382 (0.21%) ^ | ERI: sell | WAIT | Last Action: BUY | 0% (delta: 53521.3)
2021-04-26 23:06:21 | BTC-USD (BEAR) | 3600 | Current Price: 53617.66
2021-04-26 23:11:22 | BTC-USD (BEAR) | 3600 | Current Price: 53721.53
2021-04-26 23:16:23 | BTC-USD (BEAR) | 3600 | Current Price: 53721.9
2021-04-26 23:21:24 | BTC-USD (BEAR) | 3600 | Current Price: 53887.99
2021-04-26 23:26:25 | BTC-USD (BEAR) | 3600 | Current Price: 53919.51
2021-04-26 23:31:26 | BTC-USD (BEAR) | 3600 | Current Price: 53811.65
2021-04-26 23:36:28 | BTC-USD (BEAR) | 3600 | Current Price: 53908.73
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-26 23:41:29 | BTC-USD (BEAR) | 3600 | Current Price: 53937.73
2021-04-26 23:46:30 | BTC-USD (BEAR) | 3600 | Current Price: 54000.64
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-26 23:51:31 | BTC-USD (BEAR) | 3600 | Current Price: 54007.65
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-26 23:56:49 | BTC-USD (BEAR) | 3600 | Current Price: 54051.62
2021-04-27 00:01:51 | BTC-USD (BEAR) | 3600 | Current Price: 54055.42
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 | BTC-USD (BEAR) | 3600 | Close: 54115.53 | ^ EMA12/26: 53662.21 > 52949.81 ^ | v MACD: 712.39 < 797.98 v | v OBV: -11620.2760 (-0.71%) v | ERI: buy | WAIT | Last Action: BUY | 0% (delta: 54115.53)
2021-04-27 00:11:53 | BTC-USD (BEAR) | 3600 | Current Price: 53915.33
2021-04-27 00:16:54 | BTC-USD (BEAR) | 3600 | Current Price: 53763.97
2021-04-27 00:21:55 | BTC-USD (BEAR) | 3600 | Current Price: 53901.19
2021-04-27 00:26:56 | BTC-USD (BEAR) | 3600 | Current Price: 53710.0
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 00:31:57 | BTC-USD (BEAR) | 3600 | Current Price: 53799.99
2021-04-27 00:36:58 | BTC-USD (BEAR) | 3600 | Current Price: 53898.53
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 00:41:59 | BTC-USD (BEAR) | 3600 | Current Price: 53920.42
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 00:47:41 | BTC-USD (BEAR) | 3600 | Current Price: 53756.21
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 00:52:49 | BTC-USD (BEAR) | 3600 | Current Price: 53754.69
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 00:58:31 | BTC-USD (BEAR) | 3600 | Current Price: 53760.28
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
* Candlestick Detected: Hammer ("Weak - Reversal - Bullish Signal - Up") 

2021-04-27 01:00:00 | BTC-USD (BEAR) | 3600 | Close: 53744.23 | ^ EMA12/26: 53621.49 > 52980.55 ^ | v MACD: 640.93 < 761.34 v | v OBV: -9366.5981 (-0.2%) v | ERI: sell | WAIT | Last Action: BUY | 0% (delta: 53744.23)
2021-04-27 01:08:33 | BTC-USD (BEAR) | 3600 | Current Price: 53812.85
2021-04-27 01:13:34 | BTC-USD (BEAR) | 3600 | Current Price: 53804.77
2021-04-27 01:18:35 | BTC-USD (BEAR) | 3600 | Current Price: 53830.0
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 01:23:42 | BTC-USD (BEAR) | 3600 | Current Price: 53743.36
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 01:28:47 | BTC-USD (BEAR) | 3600 | Current Price: 53774.11
2021-04-27 01:33:48 | BTC-USD (BEAR) | 3600 | Current Price: 53662.11
2021-04-27 01:38:49 | BTC-USD (BEAR) | 3600 | Current Price: 53733.81
2021-04-27 01:43:50 | BTC-USD (BEAR) | 3600 | Current Price: 53711.2
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 01:49:04 | BTC-USD (BEAR) | 3600 | Current Price: 53798.08
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 01:54:06 | BTC-USD (BEAR) | 3600 | Current Price: 53813.57
2021-04-27 01:59:07 | BTC-USD (BEAR) | 3600 | Current Price: 53649.98
2021-04-27 02:00:00 | BTC-USD (BEAR) | 3600 | Close: 53826.33 | ^ EMA12/26: 53677.66 > 53055.62 ^ | v MACD: 622.03 < 734.66 v | v OBV: -10980.7613 (-0.23%) v | ERI: buy | WAIT | Last Action: BUY | 0% (delta: 53826.33)
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 02:09:09 | BTC-USD (BEAR) | 3600 | Current Price: 53961.89
error: GET (500) https://api.pro.coinbase.com/products/BTC-USD/ticker - Internal server error
2021-04-27 02:14:37 | BTC-USD (BEAR) | 3600 | Current Price: 53957.79
2021-04-27 02:19:38 | BTC-USD (BEAR) | 3600 | Current Price: 53903.16
Traceback (most recent call last):
  File "pycryptobot.py", line 885, in <module>
    s.run()
  File "/usr/lib64/python3.8/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "pycryptobot.py", line 178, in executeJob
    price = app.getTicker(app.getMarket())
  File "/app/models/PyCryptoBot.py", line 1136, in getTicker
    return api.getTicker(market)
  File "/app/models/CoinbasePro.py", line 477, in getTicker
    resp = self.authAPI('GET','products/' + market + '/ticker')
  File "/app/models/CoinbasePro.py", line 513, in authAPI
    print('error:', method.upper() + ' (' + '{}'.format(resp.status_code) + ') ' + self.api_url + uri + ' - ' + '{}'.format(resp.json()['message']))
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by iThom** [comment]
Hello,

There your json decode error is not related to your json configuration file but to the response of the Coinbase Pro API which is also in json. As you can see in your logs, some api calls went wront and got a 500 error.

**Comment by jazha** [comment]
This was fixed yesterday I believe, update your local copy to the current one.

https://github.com/whittlem/pycryptobot/commit/3241dab9aebd4230d44e9ad27041b47ac28ab7b6

**Comment by djgalloway** [comment]
> This was fixed yesterday I believe, update your local copy to the current one.

Rockin!  Thank you!
