### ISSUE TITLE
Data range too small

### ISSUE THREAD

**Issue by p9qgtjaliucdtygqapv79h5nm1faov8** [whittlem/pycryptobot#90]
```
ConnectionError: https://api.pro.coinbase.com/
Traceback (most recent call last):
  File "pycryptobot.py", line 916, in <module>
    s.run()
  File "/usr/lib64/python3.8/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "pycryptobot.py", line 98, in executeJob
    ta.addAll()
  File "/app/models/Trading.py", line 46, in addAll
    self.addSMA(20)
  File "/app/models/Trading.py", line 498, in addSMA
    raise Exception('Data range too small.')
Exception: Data range too small.
```

I ran into a strange issue while trying to use this bot on ALGO-USD. The bot was running before and had no issues. When I restarted the bot resumed working. I've had this issue with BAT-USD and ADA-USD as well, but they would throw this exception when they start. An approximate timestamp for this issue was 2021-04-29 02:44:15.

**Comment by whittlem** [comment]
I'm assuming with the market format this is Coinbase and not Binance. You would get this error if for any reason the exchange does not provide the expected historical data back. If you are trading the hourly graphs for example if you retrieve less than 300 hours of data it will throw this error. If this was working previously maybe the exchange returned incomplete data for some reason.
